CREATE DATABASE IF NOT EXISTS `habit_snowball`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `habit_snowball`;

CREATE TABLE IF NOT EXISTS `user_states` (
  `user_key` VARCHAR(120) NOT NULL PRIMARY KEY,
  `payload` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
